In [1]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import NearestNeighbors
import numpy as np
import csv

In [2]:
file1 = 'lenses.training'
file2 = 'lenses.testing'
k = 2

In [3]:
def read_file(file):
    X = []
    with open(file) as f:
        for line in f:
            item = line.strip().split(',')
            item = [int(i) for i in item]
            X.append(item)
        return np.asarray(X)

In [19]:
def group_training_data(X):
    y = X[:, [4]]
    y = np.reshape(y, -1)
    return np.asarray(y)

In [24]:
def handler(X, y, source):
    neigh = KNeighborsClassifier(n_neighbors=k, p=2, metric='minkowski')
    nearest_neigh = NearestNeighbors(n_neighbors=1, p=2, metric='minkowski')

    neigh.fit(X, y)
    nearest_neigh.fit(X)
    f = open(file2, 'w')
    datawriter = csv.writer(f, delimiter=',')
    for i in source:
        item = np.asarray(i).reshape(1, -1)
        result = []
        result.append(nearest_neigh.kneighbors(item, return_distance=False)[0][0] + 1)
        result = np.append(result, item)
        result = np.append(result, neigh.predict(item)[0])
        datawriter.writerow(result)
        print(result)
    f.close()

In [26]:
X = read_file(file1)
y = group_training_data(X)
source = read_file(file2)
handler(X, y, source)

[1 1 1 2 1 3 3]
[6 1 1 2 2 1 1]
[7 2 1 2 1 3 3]
[4 2 2 1 2 2 2]
[7 3 1 1 1 3 3]
[8 3 2 1 2 2 2]


In [7]:
print(y)

[[3]
 [2]
 [3]
 [2]
 [3]
 [1]
 [3]
 [2]
 [1]
 [3]
 [3]
 [3]
 [3]
 [3]
 [1]
 [3]
 [3]
 [3]]


In [130]:
print(type(int(y[0])))

<class 'int'>


In [128]:
A = [1, 2]
print(type(A[0]))

<class 'int'>
