In [52]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import NearestNeighbors
import numpy as np

In [59]:
def read_file(file):
    X = []
    with open(file) as f:
        for line in f:
            item = line.strip().split(',')
            item = [int(i) for i in item]
            X.append(item)
        return np.asarray(X)

In [60]:
def group_training_data(X):
    y = []
    group_size = int(len(X) / 4)
    for i in range(0, 4):
        if (i == group_num - 1):
            while (len(y) != len(X)):
                y.append(group_size - 1)
        else:
            for j in range(0, group_size):
                if (len(y) == len(X)):
                    break
                else:
                    y.append(i)
    return np.asarray(y)

In [61]:
X = read_file('lenses.training')
y = group_training_data(X)
source = read_file('lenses.testing')

In [62]:
print(np.asarray(source[0]).reshape(1, -1))
print(X)

[[1 1 2 1 3]]
[[1 1 1 1 3]
 [1 1 1 2 2]
 [1 2 1 1 3]
 [1 2 1 2 2]
 [1 2 2 1 3]
 [1 2 2 2 1]
 [2 1 1 1 3]
 [2 1 1 2 2]
 [2 1 2 2 1]
 [2 2 1 1 3]
 [2 2 2 1 3]
 [2 2 2 2 3]
 [3 1 1 2 3]
 [3 1 2 1 3]
 [3 1 2 2 1]
 [3 2 1 1 3]
 [3 2 2 1 3]
 [3 2 2 2 3]]


In [66]:
neigh = KNeighborsClassifier(n_neighbors=2)
nearest_neigh = NearestNeighbors(n_neighbors=1)

neigh.fit(X, y)
nearest_neigh.fit(X)
for i in source:
    item = np.asarray(i).reshape(1, -1)
    print(item)
    print(neigh.predict(item), " ", nearest_neigh.kneighbors(item))

[[1 1 2 1 3]]
[0]   (array([[ 1.]]), array([[0]]))
[[1 1 2 2 1]]
[1]   (array([[ 1.]]), array([[5]]))
[[2 1 2 1 3]]
[1]   (array([[ 1.]]), array([[6]]))
[[2 2 1 2 2]]
[0]   (array([[ 1.]]), array([[3]]))
[[3 1 1 1 3]]
[1]   (array([[ 1.]]), array([[6]]))
[[3 2 1 2 2]]
[1]   (array([[ 1.41421356]]), array([[7]]))
